Readme:
1. 'array' means numpy array data type: numpy.array()
2. 'list' means python list data type: list()

We encourage you to explore more functionalities in 'Python for Data Analysis, 3E' by Wes McKinney, Chapter 4: 'NumPy Basics: Arrays and Vectorized Computation'.</br>
Link: https://wesmckinney.com/book/numpy-basics

In [33]:
!pip install numpy

In [1]:
import numpy as np

<p>
Create a python list in range 1_000_000. </br>
Then multiply each element by 2 and measure the execution time with the help of magic command %timeit.</br>
</p>


In [35]:
lst = list(range(1_000_000))
%timeit lst2 = [i * 2 for i in lst] 

87.3 ms ± 1.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


<p>
Now create a numpy array in range 1_000_000. </br>
Then multiply each element by 2 and measure the execution time.</br></br>
Then compare the multiplication execution time of numpy array and python list. Which one is faster?</br>
Do you have to use a for loop for the multiplication operation with numpy arrays?</br>
</p>


In [36]:
arr = np.arange(1_000_000)
%timeit arr2 = arr * 2

1.53 ms ± 46.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)



<p>
Create a numpy array out of [1.5, -0.1, 3], [0, -3, 6.5]. Then do: </br>
1. Add each element to itself;</br>
2. Multiply each element by 10.</br>
3. How many dimentions does the array have? Use proper numpy attributes to return the answer.</br>

</p>


In [2]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print(data + data)
print(data * 10)
print(data.ndim) # or: print(data.shape)

[[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]
[[ 15.  -1.  30.]
 [  0. -30.  65.]]
2


<p>
Create an array of zeros in the following shape: </br>
[[0. 0. 0. 0. 0. 0.]</br>
 [0. 0. 0. 0. 0. 0.]</br>
 [0. 0. 0. 0. 0. 0.]]</br></br>
Hint: </br>
numpy.empty() serves a different purpose. It creates an array without initializing its values to any particular value, so it’s not safe to assume that it will return an array of all zeros. 
This function returns uninitialized memory and thus may contain nonzero "garbage" values. You should use this function only if you intend to populate the new array with data.




</p>


In [38]:
arr = np.zeros((3, 6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

<p>
Create an array of ones in the following shape: </br>
[[1., 1.],</br>
 [1., 1.]]</br>





</p>


In [39]:
arr = np.ones((2, 2))
arr

array([[1., 1.],
       [1., 1.]])

<p>
Create an array with shape(2, 2) where all values are equal to 10 </br>



</p>


In [40]:
arr = np.full((2, 2), 10)
arr

array([[10, 10],
       [10, 10]])

<p>
Create an array in the following shape: </br>
[[1. 0. 0.]</br>
[0. 1. 0.]</br>
[0. 0. 1.]]</br>



</p>


In [41]:
arr = np.eye(3) # or arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<p>
Create array out of numbers 1, 2, 3, 4, 5, then display its data type. </br>
Then convert the data type to float64 and display the data type.</br>



</p>


In [42]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype('float64')
print(arr.dtype)

int32
float64


<p>
Create a python list in range of 100. </br>
Assign a scalar value of 1001 to the list elements with index 75, 76, 77, 78, 79, 80</br></br>


</p>


In [ ]:
l = list(range(100))
l[75:80] = [1001, 1001, 1001, 1001, 1001, 1001] # or: [1001]*len(l[75:80])
l

<p>
Now create a numpy array in range of 100. </br>
Assign a scalar value of 1001 to the array elements with index 75, 76, 77, 78, 79, 80</br></br>
Compare the assignment syntax with the one used with the python list.

</p>


In [44]:
arr = np.arange(100)
arr[75:80] = 1001
arr

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74, 1001, 1001,
       1001, 1001, 1001,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99])

<p>
Create an array out of the following names: "Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe".</br>
Return a boolean array where 'True' indicates the position of 'Bob': </br>
Output result: [ True, False, False,  True, False, False, False]</br></br>
How would you do it if it was a python list?



</p>


In [47]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names == 'Bob'

array([ True, False, False,  True, False, False, False])

<p>
What if you want to return a boolean array where 'True' indicates the position of 'Bob' or 'Will'?</br>

</p>


In [52]:
(names == 'Bob') | (names == 'Will')

array([ True, False,  True,  True,  True, False, False])

<p>
Create an integer array out of [4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4].</br>
Select values from the integer array where value in the names array is 'Bob' (see the previous tasks).</br>

</p>


In [104]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
print(data[names == "Bob"])

[[4 7]
 [0 0]]


<p>
Run below piece of code and analyse the result:</br>




</p>


In [105]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

print(data[names == "Bob", 1:])
print(data[names == "Bob", 1])

[[7]
 [0]]
[7 0]


<p>
Create an array out of [4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4].</br>
Assign 0 to the values that are less then 0.</br>



</p>


In [54]:
arr = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
arr[arr < 0] = 0
arr

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

<p>
Create an array in range of 32 with shape(8, 4).</br>
1. Return the value of 4 using indexing.</br>
2. Return the value of 23 using indexing.</br>
3. Return the value of 29 using indexing.</br>
4. Return the value of 10 using indexing.</br>
5. Now using indexing, return the values of 4, 23, 29, 10 all together using one line of code</br></br>
Think of how would you do it using a python list and compare the syntax.

</p>


In [106]:
arr = np.arange(32).reshape((8, 4))
print(arr)
print(arr[1,0])
print(arr[5,3])
print(arr[7,1])
print(arr[2,2])
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]]) # == (1, 0), (5, 3), (7, 1), (2, 2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
4
23
29
10
[ 4 23 29 10]


<p>
Create two arrays 'x' and 'y' with size 8 each populated with random float numbers with the help of numpy.random.standard_normal().</br>
1. Return the maximum value by comparing the two arrays.</br>
2. From array 'x', return an array containing the whole parts of the float, and another array containing the remainders. E.g. in float -0.60869751 whole part is -0, and remainder is -0.60869751</br>
</p>


In [82]:
x = np.random.standard_normal(8)
y = np.random.standard_normal(8)
print(np.maximum(x,y))
remainder, whole_part = np.modf(x)
print(remainder, whole_part)    

[ 0.50018473  0.90787665 -0.60869751  0.82298375  0.17933299 -0.69670322
 -0.72832579 -0.72729416]
[ 0.50018473  0.90787665 -0.60869751  0.82298375  0.17933299 -0.69670322
 -0.72832579 -0.72729416] [ 0.  0. -0.  0.  0. -0. -0. -0.]


<p>
Given below arrays, return a python list that takes a value from xarr whenever the corresponding value in cond is True, and otherwise takes the value from yarr.</br>
Use list comprehension technique and time it.</br></br>

Hint: this has multiple problems. First, it will not be very fast for large arrays (because all the work is being done in interpreted Python code). 
Second, it will not work with multidimensional arrays.</br>


</p>


In [86]:
xarr = np.random.standard_normal(1_000_000)
yarr = np.random.standard_normal(1_000_000)
cond = np.random.choice(a=[True, False], size=1_000_000)
#cond = np.array([True, False, True, True, False])
%timeit l = [x if c else y for x, c, y in zip(xarr, yarr, cond)]


192 ms ± 7.91 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


<p>
Now repeat the previous task, but return a numpy array this time. Measure the execution time, and compare the results..</br>




</p>


In [87]:
%timeit arr = np.where(cond, xarr, yarr)

3.47 ms ± 180 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


<p>
What is a 'row' and what is a 'column' in a multidimensional array? </br></br>
Create an array using np.random.standard_normal with size(3, 5).</br>
1. Calculate the sum of each 'row'.</br>
2. Calculate the sum of each 'column'.</br>



</p>


In [3]:
arr = np.random.standard_normal((3,5))
print(arr)
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[-0.981616    0.67553151  1.42525506 -1.51220045 -1.81272244]
 [ 0.09694457  0.63896713 -1.52039536  1.7264579  -1.1550095 ]
 [ 1.09371368 -0.19936445  0.40656001 -0.62948237 -0.36804779]]
[ 0.20904224  1.11513419  0.31141971 -0.41522493 -3.33577973]
[-2.20575232 -0.21303526  0.30337908]


<p>
Boolean values are coerced to 1 (True) and 0 (False). Thus, sum is often used as a means of counting True values in a Boolean array.</br>
1. Create an array using np.random.standard_normal with size 100.</br>
2. Return the count of values that are greater than zero and the count of values that are less or equal to zero.</br>

</p>


In [4]:
arr = np.random.standard_normal(100)
print((arr > 0).sum())
print((arr <= 0).sum())

#consider adding any, all - or as part of advanced tasks

48
52


<p>
Create an array using np.random.standard_normal with size(8, 10) and sort the values within each column.</br>




</p>


In [98]:
arr = np.random.standard_normal((8,10))
arr.sort(axis=1) # sorts in place!
print(arr)

[[-0.69276104 -0.46490143 -0.26862972  0.1812811   0.23357313  0.255606
   0.4130779   1.03141821  1.07556712  2.64449258]
 [-0.73395947 -0.54599855 -0.42034314 -0.40245091 -0.33759617 -0.27271383
  -0.10466879  0.28946018  0.711644    1.06290972]
 [-0.81685333 -0.21418687 -0.13595633 -0.1199563  -0.03225136  0.05811347
   0.1487667   0.23709511  0.43612481  1.99540529]
 [-1.50494183 -0.92605237 -0.26133185 -0.15994278  0.03524418  0.24870476
   0.38620332  0.8362589   0.94384792  1.50417163]
 [-2.34044603 -1.75601943 -0.23709661 -0.13407262  0.29693722  0.35789441
   0.99353895  1.13889789  1.41206178  1.73728671]
 [-0.98802148 -0.90989484 -0.61061243 -0.42131421 -0.41239459  0.18904773
   0.27496457  0.34154649  0.41331789  0.7707368 ]
 [-2.76415143 -1.46616629 -0.3874783  -0.15855232 -0.0655165   0.48966003
   0.50693253  0.8535298   1.05992879  1.58911691]
 [-1.08283645 -0.96401427 -0.88319161 -0.25105693 -0.17454668  0.11968631
   0.36438916  0.65306271  0.98861927  2.50762099]]


<p>
Create an array of names "Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe".</br>
Then return an array with unique value only.</br>




</p>


In [100]:
arr = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(arr)

array(['Bob', 'Joe', 'Will'], dtype='<U4')